name: smk-starter
version: '1.0'
summary: My summary
description: 'A simple starter project for the SMK library.'
grade: stable
confinement: strict
base: core20

apps:
  smk-starter:
    command: bin/desktop-launch $SNAP/usr/bin/smk-starter
    plugs:
    - audio-playback
    - opengl
    - pulseaudio
    - x11

parts:

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  smk-starter:
    after:
    - desktop-glib-only
    plugin: cmake
    source: https://github.com/ArthurSonzogni/smk-starter
    source-type: git
    stage-packages:
      - libgl1-mesa-glx
      - libopengl0
      - libpulse0
    build-packages:
      - libglu1-mesa-dev
      - libpulse-dev
      - xorg-dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git rev-list --count HEAD)
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release

passthrough:
  title: smk-starter
  license: MIT
