name: smk-starter
version: '1.0'
summary: My summary
description: 'A simple starter project for the SMK library.'
grade: stable
confinement: strict
base: core18

apps:
  smk-starter:
    command: desktop-launch ${SNAP}/bin/smk-starter
    plugs:
    - audio-playback
    - opengl
    - pulseaudio
    - x11

parts:

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  smk-starter:
    after:
    - desktop-glib-only
    plugin: cmake
    build-snaps: [cmake/latest/edge] # We need cmake >= 3.11
    source: https://github.com/ArthurSonzogni/smk-starter
    source-type: git
    source-depth: 1
    stage-packages:
    - libgl1-mesa-glx
    - libpulse0
    build-packages:
    - libglu-dev
    - libpulse-dev
    - xorg-dev
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install

passthrough:
  title: smk-starter
  license: MIT
