name: smk-starter
version: '1.0'
summary: My summary
description: |
  A simple starter project for the SMK library.

grade: stable
confinement: strict
base: core18
apps:
  smk-starter:
    command: ./bin/smk-starter
    plugs:
      - audio-playback
      - opengl
      - x11
parts:
  # Build cmake from source to get a recent version.
  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install
    build-packages:
      - build-essential
      - libssl-dev
      - libncurses5-dev
    stage-packages:
      - libssl1.1
      - libncurses5
      - libtinfo5
    prime: []

  smk-starter:
    after: [cmake]
    plugin: cmake
    source: https://github.com/ArthurSonzogni/smk-starter
    source-type: git
    source-depth: 1
    stage-packages:
      - libgl1-mesa-glx
    build-packages:
      - libglu-dev
      - xorg-dev
    override-build: |
      $SNAPCRAFT_STAGE/cmake/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install

passthrough:
  title: smk-starter
  license: MIT
